[buildPlans.AkvesoiCode]
family = "Akvesoi Code"
desc = "Default"
buildCharMap = true
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 0}
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiCode.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "tall-slashed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-w = "straight-vertical-sides-serifless"
f = "flat-hook-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
r = "hookless-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
lower-gamma = "straight"
lower-mu = "toothed-serifless"
asterisk = "penta-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiCode.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiTerm]
family = "Akvesoi Term"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.AkvesoiTerm.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "tall-slashed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-w = "straight-vertical-sides-serifless"
f = "flat-hook-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
r = "hookless-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
lower-gamma = "straight"
lower-mu = "toothed-serifless"
asterisk = "penta-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiTerm.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiMono]
family = "Akvesoi Mono"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.AkvesoiMono.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "tall-slashed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-w = "straight-vertical-sides-serifless"
f = "flat-hook-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
r = "hookless-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
lower-gamma = "straight"
lower-mu = "toothed-serifless"
asterisk = "penta-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiType]
family = "Akvesoi Type"
desc = "Slab-serif"
spacing = "quasi-proportional-extension-only"
serifs = "slab"
snapshotFamily = 'Akvesoi'
snapshotFeature = {"NWID" = 0}
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiType.variants.design]
three = "flat-top-serifed"
five = "oblique-arched-serifed"
six = "closed-contour"
seven = "straight-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "tall-slashed"
capital-d = "standard-bilateral-serifed"
capital-g = "toothless-corner-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-q = "crossing"
capital-r = "standing-serifed"
capital-w = "straight-vertical-sides-serifed"
f = "flat-hook-serifed"
g = "single-storey-serifed"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifed"
r = "hookless-serifed"
t = "flat-hook"
u = "toothed-serifed"
w = "straight-flat-top-serifed"
lower-gamma = "straight"
lower-mu = "toothed-serifed"
asterisk = "penta-low"
ascii-grave = "raised-turn-comma"
ascii-single-quote = "raised-comma"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"
punctuation-dot = "square"
ampersand = "closed"

[buildPlans.AkvesoiType.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiType.widths.Normal]
shape = 600
menu = 5
css = "normal"

[collectPlans.Akvesoi]
release = true
from = ["AkvesoiCode", "AkvesoiTerm", "AkvesoiMono", "AkvesoiType"]
