[buildPlans.AkvesoiCode]
family = "Akvesoi Code"
desc = "Default"
buildCharMap = true
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 0}
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiCode.variants]
inherits = "ss14"

[buildPlans.AkvesoiCode.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
zero = "slashed"
capital-d = "more-rounded-serifless"
capital-k = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
k = "straight-serifless"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
dollar = "open-cap"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiCode.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiTerm]
family = "Akvesoi Term"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.AkvesoiTerm.variants]
inherits = "ss14"

[buildPlans.AkvesoiTerm.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
zero = "slashed"
capital-d = "more-rounded-serifless"
capital-k = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
k = "straight-serifless"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
dollar = "open-cap"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiTerm.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiTerm.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiMono]
family = "Akvesoi Mono"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.AkvesoiMono.variants]
inherits = "ss14"

[buildPlans.AkvesoiMono.variants.design]
three = "two-arcs"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
zero = "slashed"
capital-d = "more-rounded-serifless"
capital-k = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
k = "straight-serifless"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
dollar = "open-cap"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiType]
family = "Akvesoi Type"
desc = "Slab-serif"
spacing = "quasi-proportional-extension-only"
serifs = "slab"
snapshotFamily = 'Akvesoi'
snapshotFeature = {"NWID" = 0}
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiType.variants.design]
three = "flat-top-serifed"
five = "oblique-arched-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-k = "straight-serifless"
capital-w = "straight-vertical-sides-serifed"
i = "serifed-flat-tailed"
w = "straight-vertical-sides-serifed"
punctuation-dot = "square"
asterisk = "hex-low"
ascii-grave = "raised-turn-comma"
ascii-single-quote = "raised-comma"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
dollar = "open-cap"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "flat"

[buildPlans.AkvesoiType.ligations]
enables = ["hash-hash", "underscore-underscore", "plus-plus-plus", "minus-minus-minus", "tilde-tilde", "brack-bar", "brace-bar", "html-comment", "llggeq", "llgg", "logic", "kern-bars", "kern-dotty", "slash-asterisk", "brst", "ltgt-slash-tag", "ltgt-diamond", "exeq", "lteq", "gteq", "eqeq", "trig", "center-op-trigger-equal-l", "center-op-trigger-equal-r", "arrow-l", "arrow-r", "arrow-lr" ]

[buildPlans.AkvesoiType.widths.Normal]
shape = 600
menu = 5
css = "normal"

[collectPlans.Akvesoi]
release = true
from = ["AkvesoiCode", "AkvesoiTerm", "AkvesoiMono", "AkvesoiType"]
